#!/bin/bash

# it is not hard to overcome this. This is for letting the user know in advance that the installation will fail (license is checked at startup)
LICENSE_CHECKER_CP=""
for i in /usr/share/abraflexi/lib/postgresql-*.jar /usr/share/abraflexi/lib/winstrom-connector-*.jar /usr/share/abraflexi/lib/LicenseChecker.jar; do
	LICENSE_CHECKER_CP=$LICENSE_CHECKER_CP:$i
done

OK=true
/usr/bin/java -cp $LICENSE_CHECKER_CP cz.winstrom.Checker /usr/share/abraflexi/lib/winstrom-connector*.jar || OK=false
if [ x$OK = xfalse ]; then
    echo ""
    if [ "x$MYLANG" = "xcs" ]; then
	echo "  Chyba: Pokoušíte se aktualizovat na novější verzi systému abraflexi než vás opravňuje zaplacená služba záruka. Vraťte původní verzi a nebo kontaktujte dodavatele systému a prodlužte si záruku.";
    else 
	echo "  Error: You are trying to update to a newer version of abraflexi system than allowed in your license. Please put back the original version or contact the producer and prolong your license.";
    fi
    echo ""
    exit 1
fi