#!/bin/bash

set -e

TYPE=client

# check if PostgreSQL cluster is installed.
if [ -f /usr/bin/pg_createcluster ]; then 

       . /usr/share/debconf/confmodule

	# ask user for local database
	db_input high winstrom/local-network || true
	db_go || true

	db_get winstrom/local-network 
    
	if [ "x$RET" = "xnetwork" ]; then
		db_input high winstrom/server-client || true
		db_go || RET=true
		db_get winstrom/server-client 
		if [ "x$RET" = "xserver" ]; then
		    TYPE="server"
		else
		    TYPE="client"
		fi
	else
	    TYPE="local"
	fi

fi

CFG=/etc/default/flexibee
if [ -f "$CFG" ]; then
cat $CFG | sed "s/#*[[:space:]]*FLEXIBEE_CFG=.*/FLEXIBEE_CFG=$TYPE/g" > $CFG.new
CONFIG_CHANGED=0
/usr/bin/diff -q --ignore-space-change $CFG $CFG.new > /dev/null 2> /dev/null || CONFIG_CHANGED=1

if [ "x$CONFIG_CHANGED" = "x1" ]; then
    mv $CFG $CFG.old
    mv $CFG.new $CFG
else
    rm "$CFG.new"
fi
fi

exit 0
