#!/bin/bash

. /usr/share/debconf/confmodule

set -e

if [ -x /etc/init.d/flexibee ]; then
    /etc/init.d/flexibee stop || true
fi

if [ -x /etc/init.d/winstrom ]; then
    /etc/init.d/winstrom stop || true
fi

if [ -f /usr/bin/xdg-desktop-menu ]; then
    /usr/bin/xdg-desktop-menu uninstall --novendor /usr/share/applications/flexibee.desktop > /dev/null  || true
fi

if [ -f /usr/bin/xdg-mime ]; then
    /usr/bin/xdg-mime uninstall --novendor /usr/share/mime/packages/flexibee.xml > /dev/null  || true
fi


if [ -f /usr/bin/xdg-icon-resource ]; then
    /usr/bin/xdg-icon-resource uninstall --context mimetypes --size 128 flexibee-backup
    /usr/bin/xdg-icon-resource uninstall --context mimetypes --size 128 flexibee-license
    /usr/bin/xdg-icon-resource uninstall --context mimetypes --size 128 flexibee-query
    /usr/bin/xdg-icon-resource uninstall --context mimetypes --size 128 flexibee-report
    /usr/bin/xdg-icon-resource uninstall --context mimetypes --size 128 flexibee-xml
    /usr/bin/xdg-icon-resource uninstall --context mimetypes --size 128 flexibee-isdoc

    /usr/bin/xdg-icon-resource uninstall --context mimetypes --size 128 winstrom-backup
    /usr/bin/xdg-icon-resource uninstall --context mimetypes --size 128 winstrom-license
    /usr/bin/xdg-icon-resource uninstall --context mimetypes --size 128 winstrom-xml
fi

# backup changes in FlexiBee installation type done manually by user [Bug 41596 - Aktualizace FlexiBee balíčku na linuxu resetuje nastavení FLEXIBEE_CFG (typ instalace se vrací na local)]
if [ -f /etc/default/flexibee ]; then
    . /etc/default/flexibee
    
    if [ "x$FLEXIBEE_CFG" == "xlocal" ]; then
        db_set winstrom/local-network "local"
    else
	db_set winstrom/local-network "network"
	if [ "x$FLEXIBEE_CFG" == "xserver" ]; then
            db_set winstrom/server-client "server"
        else 
            db_set winstrom/server-client "client"
        fi
    fi
fi